maps/de_town_arco.res
maps/de_town_arco.txt
models/de_town_arco/lantern.mdl
models/de_town_arco/pepper_axe.mdl
models/de_town_arco/puit.mdl
models/de_town_arco/tree_gshaded.mdl
models/de_town_arco/tree_japan_round.mdl
gfx/env/mpa_dust01_csbk.tga
gfx/env/mpa_dust01_csdn.tga
gfx/env/mpa_dust01_csft.tga
gfx/env/mpa_dust01_cslf.tga
gfx/env/mpa_dust01_csrt.tga
gfx/env/mpa_dust01_csup.tga
